Create cognito module
ima-tech/pristine-ts pull request #17
Opened 2021-05-03 13:21 UTC by mathieugh

2021-05-05 19:39 UTC, mathieugh commented on packages/aws-cognito/src/authenticators/aws-cognito.authenticator.ts
> +    }
@etiennenoel on fait quoi avec ca ? Entre autre pour les erreurs ?

2021-05-05 19:40 UTC, mathieugh commented on packages/networking/src/router.ts
> +            }
@etiennenoel ici on verifie juste pour unauthorized error ?

2021-05-05 21:48 UTC, Maxime-Gosselin approved these changes

2021-05-05 21:48 UTC, Maxime-Gosselin commented on packages/networking/src/interfaces/router.interface.ts
> +import {RequestInterface} from "@pristine-ts/common/dist/lib/esm/interfaces/request.interface";
Le path est avec dist ? ou on peut juste mettre @pristine-ts/common ?

2021-05-05 21:48 UTC, Maxime-Gosselin commented on packages/networking/src/models/request.ts
> +import {RequestInterface} from "@pristine-ts/common/dist/lib/esm/interfaces/request.interface";
same

2021-05-05 21:48 UTC, Maxime-Gosselin commented on packages/networking/src/models/response.ts
> +import {RequestInterface} from "@pristine-ts/common/dist/lib/esm/interfaces/request.interface";
same

2021-05-05 22:57 UTC, etiennenoel commented on packages/networking/src/interfaces/router.interface.ts
> +import {RequestInterface} from "@pristine-ts/common/dist/lib/esm/interfaces/request.interface";
good catch faut pas que ça soit dist!

2021-05-05 22:58 UTC, etiennenoel commented on packages/aws-cognito/src/authenticators/aws-cognito.authenticator.ts
> +    }
On throw une erreur pour l'instant et ensuite on va se faire un objet httpError qu'on va handle et bien retourner.

2021-05-06 00:16 UTC, etiennenoel requested changes

2021-05-06 12:05 UTC, mathieugh commented on packages/networking/src/models/response.ts
> +import {RequestInterface} from "@pristine-ts/common/dist/lib/esm/interfaces/request.interface";
Good catch !

2021-05-06 12:54 UTC, etiennenoel approved these changes
LGTM

2021-05-06 13:56 UTC, mathieugh commented on packages/aws-cognito/src/authenticators/aws-cognito.authenticator.spec.ts
> +import "reflect-metadata"
Hehe merci merci

2021-05-06 14:00 UTC, merged